### ISSUE TITLE
Question about growth prediction for Eukaryotes

### ISSUE THREAD

**Issue by susheelbhanu** [jlw-ecoevo/gRodon2#1]
Hey @jlw-ecoevo,

Firstly, thank you for upgrading `gRodon` to include estimations for Eukaryotes. Is there an alternate vignette for running the Euks or does one simply use the method established previously (`predictGrowth`) for the prokaryotes?

Also, will a simple reinstall of `gRodon2` suffice or will we need additional scripts?

Thank you very much!

**Comment by jlw-ecoevo** [comment]
I need to edit the vignette a little but the only real difference is the you should run it with the option `mode="eukaryote"`

you can find this info by typing `?predcitGrowth` to get the helpfile

I also strongly recommend that you include a temperature in your prediction when using eukaryote mode

**Comment by susheelbhanu** [comment]
Awesome - thank you. And just to clarify, the temperature in this case would be that of the sample environmental conditions, right?!

**Comment by jlw-ecoevo** [comment]
Yes if you are using metagenomes to get community predictions - if predicting off MAGs or genomes should be your best guess at optimal growth temp (which could also just be conditions under which the organism was samples)

**Comment by susheelbhanu** [comment]
Got it! Thanks again, Jake.
