### ISSUE TITLE
Output says genes aren't multiples of 3 or are too short, but is not the case?

### ISSUE THREAD

**Issue by scubalaina** [jlw-ecoevo/gRodon2#11]
[AG-538-A02_orf_nucl_fx.fna.txt](https://github.com/jlw-ecoevo/gRodon2/files/14828122/AG-538-A02_orf_nucl_fx.fna.txt)
Hi there! 

I'm running gRodon2 on some SAG data. I've started to test it out a couple SAGs. I'm using "ribosom" to grep of highly expressed genes. In my one SAG, there are 35 genes that meet this criteria, and I noticed that I receive the warning from gRodon  the length of 33 of these 35 genes are either too small (< 240 bp) or aren't multiples of 3. All the gene lengths are indeed multiples of 3, and only two are shorter than 240bp. The nucleotide sequences of the genes were predicted with prodigal -d option , and the annotations were HMM search hits against EggNOG 5.0 HMM profiles (E value cutoff 10e-5), with the prodigal gene label and NOG hit description separated by a colon (:).  I attached my input SAG gene sequences. Is something wrong with my input file such that these genes are not getting detected? If so, how should I change the input? Thank you for your time and help! Please let me know if I should provide additional information.

```
library(gRodon)
library(Biostrings)
> genes <- readDNAStringSet("AG-538-A02_orf_nucl_fx.fna")
> highly_expressed <- grepl("ribosom",names(genes),ignore.case = T)
> predictGrowth(genes, highly_expressed)
$CUBHE
[1] 0.5017281

$GC
[1] 0.3008578

$GCdiv
[1] 0.1991422

$ConsistencyHE
[1] 0.5009282

$CUB
[1] 0.5261309

$CPB
[1] -0.3666812

$FilteredSequences
[1] 33

$nHE
[1] 33

$dCUB
[1] 0.04638176

$d
[1] 10.44961

$LowerCI
[1] 8.268805

$UpperCI
[1] 13.31184

Warning messages:
1: In filterSeq(genes = genes, highly_expressed = highly_expressed,  :
  There were 33 genes either with lengths not multiples of 3 or not above length threshold (default 240bp), these genes have been ignored
2: In predictGrowth(genes, highly_expressed) :
  Estimated doubling time >5 hours. CUB signal saturates at approx. 5 hrs... gRodon may underestimate doubling times above this range. Consider simply reporting as '>5hrs'. (In other words, this microbe definitely grows slowly, but we can't tell you quite how slowly).
```

Edited to add attachment. Please remove '.txt' from handle to be loaded into R.

**Comment by jlw-ecoevo** [comment]
Hey! The 33 genes flagged includes all the genes in the genome you pass gRodon, not just the ribosomal proteins. So actually, you are getting an OK result.

The best way to confirm this is that grodon output says nHE=33. This is the number of highly expressed genes used for the growth calculation after filtering (35 minus your two short ones)

Also careful with your grep command to make sure ribosomal rRNA doesn't end up in there (should be fine if you are only passing coding sequence to gRodon).
