### ISSUE TITLE
Custom eukaryotic ribosomal protein database

### ISSUE THREAD

**Issue by susheelbhanu** [jlw-ecoevo/gRodon2#2]
Hey @jlw-ecoevo, 

It's me again. The `preprint` for gRodon_v2 states that the annotations for the eukaryotic MAGs were blasted against a **custom blast database of ribosomal proteins of eukaryotic microbes**. 

Sorry if I missed it, but is this `customDB` available somewhere? If not, would it be possible for you to share a copy?

Thank you!

**Comment by jlw-ecoevo** [comment]
https://github.com/jlw-ecoevo/eeggo/blob/main/Data/riboblastdb.tar.gz

**Comment by susheelbhanu** [comment]
Brilliant, thank you very much!
