### ISSUE TITLE
Command line invocation?

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [jlw-ecoevo/gRodon2#3]
Hi,

I'm interested in trying gRodon2 out, but I'm not much of an R user. I'd like to pass arguments to a basic R script through the command line that invokes gRodon2 rather than adding it to an existing R codebase-do you have any suggestions on how to do so? Thanks for your help!

**Comment by jlw-ecoevo** [comment]
Hi

Yes - this  would be pretty easy by writing an Rscript that takes the relevant arguments and does this using the `commandArgs()` function in R. 

For example, a minimal script to do this (full prediction mode, without any of gRodon's other options implemented) is:
```
library(Biostrings)
library(gRodon)

args = commandArgs(trailingOnly=TRUE)

genes_file <- args[1]
highly_expresssed_file <- args[2]

genes <- readDNAStringSet(genes_file)
highly_expresssed <- names(genes) %in% readLines(highly_expressed)

predictGrowth(genes,highly_expresssed)
```

Which could then be invoked from the command line as:
`Rscript minimal_gRodon.R <fasta_of_coding_seqs.fasta> <txt_file_with_names_of_seqs_coding_for_ribo_prots.txt>`

The two input files would look like this (fasta_of_coding_seqs.fasta):
```
>Seqname1
ATTGACCG...
>Seqname2
GTACCGAG...
```
and this (txt_file_with_names_of_seqs_coding_for_ribo_prots.txt)
```
Seqname100
Seqname46
Seqname2046
```

You would need to already have gRodon and it's dependencies installed to run this though. If you have particular options in the program you need implemented (e.g., temp correction) let me know and I'm happy to add to this example for you
