### ISSUE TITLE
GC content

### ISSUE THREAD

**Issue by jotech** [jlw-ecoevo/gRodon2#9]
Thank you for the gRodon package, which is really very useful for me when analyzing codon usage bias!

I have a question concerning the GC output of `predictGrowth`. What does it measure exactly? I'm asking because I'm getting different GC estimates compared to genome-wide GC estimation provided by e.g., annotation software like bakta.

Is it the GC content of the highly expressed genes? I couldn't find something in the documentation.

**Comment by jlw-ecoevo** [comment]
Yes, just genes used for prediction - I would not use in place of genome-wide GC estimates, this is just used for internal diagnostics

**Comment by jotech** [comment]
Alright, this makes sense; thank you for the clarification!
